const dummyData = [
  {
    id: 0,
    date: "2022-07-27",
    mood: "great",
    whatmakesfeel: "I was on the beach",
    notes: "I was with family",
  },
  {
    id: 1,
    date: "2022-07-28",
    mood: "great",
    whatmakesfeel: "I was on the beach",
    notes: "I was with family",
  },
  {
    id: 2,
    date: "2022-07-29",
    mood: "bad",
    whatmakesfeel: "cough covid",
    notes: "",
  },
  {
    id: 3,
    date: "2022-07-30",
    mood: "ok",
    whatmakesfeel: "pains",
    notes: "didn't eat much",
  },
  {
    id: 4,
    date: "2022-07-31",
    mood: "ok",
    whatmakesfeel: "",
    notes: "",
  },
  {
    id: 5,
    date: "2022-08-01",
    mood: "good",
    whatmakesfeel: "getting better",
    notes: "",
  },
  {
    id: 6,
    date: "2022-08-02",
    mood: "great",
    whatmakesfeel: "I was on the beach again",
    notes: "made some friends",
  },
  {
    id: 7,
    date: "2022-08-03",
    mood: "awful",
    whatmakesfeel: "my friends cough covid",
    notes: "my fault",
  },
  {
    id: 8,
    date: "2022-08-04",
    mood: "ok",
    whatmakesfeel: "testing",
    notes: "my fault",
  },
];
